{
    "ids": [
        "f374562c-927b-45ad-8cf2-9206cdc73911",
        "21475a7f-8578-4410-b83b-d593e97690d0",
        "7d9748e8-8396-4ae9-860e-c29ca4b40977",
        "c586565f-8401-4e1e-a14c-42668755503f",
    ],
    "embeddings": None,
    "documents": [
        'Generative AI Foundations\n1️⃣ API Keys, Integrations & Parameters (LLM Basics)\n1.1 What is an LLM API?\nAPI response structure (JSON)\nRequest → Model → Response flow\nStateless vs stateful calls\nToken-based pricing\nRate limits and quotas\n1.2 API Keys (Security & Usage)\nWhat an API key is\nAPI key confidentiality\nKey scopes and permissions\nKey rotation and revocation\nEnvironment variables (.env)\nServer-side vs client-side usage\n1.3 Common LLM Parameters\nmodel\ntemperature\ntop_p\nmax_tokens\nfrequency_penalty\npresence_penalty\nstop\nsystem / user / assistant roles\nDeep Dive\nTemperature vs top-p\nDeterministic outputs for production\nmax_tokens vs response length\n1.4 Error Handling & Observability\nTimeout errors\nRate limit errors\nInvalid request errors\nToken limit exceeded\nPrompt and response logging\nPrompt versioning\n2️⃣ Prompt Engineering\n2.1 Prompt Engineering Basics\nImportance of prompts\nPrompt vs question\nInstruction-following behavior\nContext window concept\n2.2 Prompt Structure\nSystem prompt\nUser prompt\nAssistant examples (few-shot)\nDelimiters (""", ``` , XML)\n2.3 Prompting Techniques\nZero-shot prompting\nFew-shot prompting\nChain-of-Thought prompting\nSelf-consistency\nRole prompting',
        '2.2 Prompt Structure\nSystem prompt\nUser prompt\nAssistant examples (few-shot)\nDelimiters (""", ``` , XML)\n2.3 Prompting Techniques\nZero-shot prompting\nFew-shot prompting\nChain-of-Thought prompting\nSelf-consistency\nRole prompting\nInstruction with constraints\n2.4 Prompt Debugging\nAmbiguous prompts\nConflicting instructions\nOverloaded prompts\n2.5 Prompt Templates\nStatic templates\nDynamic templates\nPrompt variables\nPrompt reuse\nPrompt injection risks\n3️⃣ Embeddings\n3.1 Embedding Fundamentals\nText to vector representation\nSemantic vs keyword matching\nVector dimensionality\nDeterministic embeddings\n3.2 Embedding Use Cases\nSemantic search\nSimilarity matching\nClustering\nRecommendation systems\nRetrieval Augmented Generation (RAG)\n3.3 Embedding Concepts\nTokenization\nVector space representation\nCosine similarity\nEuclidean distance\n3.4 Embedding Pipeline\nText cleaning\nText chunking\nEmbedding generation\nVector storage\nQuery embedding\nSimilarity search\n3.5 Chunking Strategies\nFixed-size chunking\nSentence-based chunking\nOverlapping chunks\nChunk size trade-offs\n3.6 Embedding Optimization\nEmbedding cost considerations\nCaching embeddings\nDeduplication\nWhen not to use embeddings\n4️⃣ Vector Databases',
        "3.5 Chunking Strategies\nFixed-size chunking\nSentence-based chunking\nOverlapping chunks\nChunk size trade-offs\n3.6 Embedding Optimization\nEmbedding cost considerations\nCaching embeddings\nDeduplication\nWhen not to use embeddings\n4️⃣ Vector Databases\n4.1 Vector Database Basics\nDifference from SQL and NoSQL\nVector indexing\nApproximate Nearest Neighbor (ANN)\n4.2 Core Concepts\nVectors\nMetadata\nIndexes\nDistance metrics\nFiltering with similarity search\n4.3 Types of Vector Databases\nManaged (Cloud)\nPinecone\nWeaviate Cloud\nQdrant Cloud\nSelf-Hosted / Open Source\nFAISS\nChroma\nQdrant\nMilvus\nHybrid (Vector + SQL)\nPostgreSQL + pgvector\nElasticsearch (dense vectors)\n4.4 Vector Database Operations\nUpsert\nDelete\nQuery\nMetadata filtering\nNamespaces / collections\n4.5 Vector Database Selection Criteria\nDataset size\nLatency requirements\nCost considerations\nCloud vs self-hosted\nFiltering capabilities\n5️⃣ Hallucinations\n5.1 Hallucination Basics\nFactual hallucinations\nFabricated information\nFalse citations\nLogical inconsistencies\n5.2 Causes of Hallucinations\nKnowledge gaps\nAmbiguous prompts\nOver-generalization\nContext limitations\nTraining cutoff\n5.3 Types of Hallucinations\nFactual hallucination",
        "Fabricated information\nFalse citations\nLogical inconsistencies\n5.2 Causes of Hallucinations\nKnowledge gaps\nAmbiguous prompts\nOver-generalization\nContext limitations\nTraining cutoff\n5.3 Types of Hallucinations\nFactual hallucination\nLogical hallucination\nSource hallucination\nInstruction hallucination\n5.4 Hallucination Mitigation\nPrompt-Level\nClear instructions\nExplicit uncertainty handling\nCitation requests\nStructured outputs\nData-Level\nRetrieval Augmented Generation\nHigh-quality context\nRelevant chunking\nModel-Level\nLower temperature\nAppropriate model selection\nSystem-Level\nOutput validation\nGuardrails\nPost-processing checks\n5.5 Evaluation & Testing\nGolden datasets\nPrompt regression testing\nManual evaluation\nHuman-in-the-loop review\n6️⃣ Types of GenAI APIs (for Integration)\nText / Chat APIs (ChatGPT, Gemini, Claude, Grok)\nEmbeddings APIs\nImage Generation APIs\nVision (Image Understanding) APIs\nAudio APIs (Speech-to-Text, Text-to-Speech)\nModeration / Safety APIs\nFine-Tuning APIs\nCloud-Hosted LLM APIs (Azure OpenAI, AWS Bedrock, Vertex AI)\nOpen-Source / Self-Hosted Model APIs",
    ],
    "uris": None,
    "included": ["metadatas", "documents"],
    "data": None,
    "metadatas": [
        {
            "access_level": 1,
            "uploaded_by": 2,
            "created_at": "2026-03-05T13:08:54.407755",
            "source": "uploads/2efca688-634b-43da-bf7d-ab714d8adbf3_Generative AI Foundations.docx",
            "chunk_index": 0,
            "classification": "internal",
            "embedding_model": "to_be_set_at_embedding_time",
            "page_number": 1,
            "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
            "chunk_id": "2efca688-634b-43da-bf7d-ab714d8adbf3_chunk_0",
            "department": "general",
        },
        {
            "source": "uploads/2efca688-634b-43da-bf7d-ab714d8adbf3_Generative AI Foundations.docx",
            "department": "general",
            "chunk_index": 1,
            "access_level": 1,
            "created_at": "2026-03-05T13:08:54.407755",
            "page_number": 1,
            "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
            "classification": "internal",
            "uploaded_by": 2,
            "chunk_id": "2efca688-634b-43da-bf7d-ab714d8adbf3_chunk_1",
            "embedding_model": "to_be_set_at_embedding_time",
        },
        {
            "created_at": "2026-03-05T13:08:54.407755",
            "access_level": 1,
            "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
            "uploaded_by": 2,
            "chunk_index": 2,
            "source": "uploads/2efca688-634b-43da-bf7d-ab714d8adbf3_Generative AI Foundations.docx",
            "department": "general",
            "chunk_id": "2efca688-634b-43da-bf7d-ab714d8adbf3_chunk_2",
            "classification": "internal",
            "embedding_model": "to_be_set_at_embedding_time",
            "page_number": 1,
        },
        {
            "uploaded_by": 2,
            "department": "general",
            "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
            "page_number": 1,
            "embedding_model": "to_be_set_at_embedding_time",
            "access_level": 1,
            "chunk_index": 3,
            "classification": "internal",
            "chunk_id": "2efca688-634b-43da-bf7d-ab714d8adbf3_chunk_3",
            "created_at": "2026-03-05T13:08:54.407755",
            "source": "uploads/2efca688-634b-43da-bf7d-ab714d8adbf3_Generative AI Foundations.docx",
        },
    ],
}
[
    {
        "content": 'Generative AI Foundations\n1️⃣ API Keys, Integrations & Parameters (LLM Basics)\n1.1 What is an LLM API?\nAPI response structure (JSON)\nRequest → Model → Response flow\nStateless vs stateful calls\nToken-based pricing\nRate limits and quotas\n1.2 API Keys (Security & Usage)\nWhat an API key is\nAPI key confidentiality\nKey scopes and permissions\nKey rotation and revocation\nEnvironment variables (.env)\nServer-side vs client-side usage\n1.3 Common LLM Parameters\nmodel\ntemperature\ntop_p\nmax_tokens\nfrequency_penalty\npresence_penalty\nstop\nsystem / user / assistant roles\nDeep Dive\nTemperature vs top-p\nDeterministic outputs for production\nmax_tokens vs response length\n1.4 Error Handling & Observability\nTimeout errors\nRate limit errors\nInvalid request errors\nToken limit exceeded\nPrompt and response logging\nPrompt versioning\n2️⃣ Prompt Engineering\n2.1 Prompt Engineering Basics\nImportance of prompts\nPrompt vs question\nInstruction-following behavior\nContext window concept\n2.2 Prompt Structure\nSystem prompt\nUser prompt\nAssistant examples (few-shot)\nDelimiters (""", ``` , XML)\n2.3 Prompting Techniques\nZero-shot prompting\nFew-shot prompting\nChain-of-Thought prompting\nSelf-consistency\nRole prompting',
        "page_number": 1,
        "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
    },
    {
        "content": '2.2 Prompt Structure\nSystem prompt\nUser prompt\nAssistant examples (few-shot)\nDelimiters (""", ``` , XML)\n2.3 Prompting Techniques\nZero-shot prompting\nFew-shot prompting\nChain-of-Thought prompting\nSelf-consistency\nRole prompting\nInstruction with constraints\n2.4 Prompt Debugging\nAmbiguous prompts\nConflicting instructions\nOverloaded prompts\n2.5 Prompt Templates\nStatic templates\nDynamic templates\nPrompt variables\nPrompt reuse\nPrompt injection risks\n3️⃣ Embeddings\n3.1 Embedding Fundamentals\nText to vector representation\nSemantic vs keyword matching\nVector dimensionality\nDeterministic embeddings\n3.2 Embedding Use Cases\nSemantic search\nSimilarity matching\nClustering\nRecommendation systems\nRetrieval Augmented Generation (RAG)\n3.3 Embedding Concepts\nTokenization\nVector space representation\nCosine similarity\nEuclidean distance\n3.4 Embedding Pipeline\nText cleaning\nText chunking\nEmbedding generation\nVector storage\nQuery embedding\nSimilarity search\n3.5 Chunking Strategies\nFixed-size chunking\nSentence-based chunking\nOverlapping chunks\nChunk size trade-offs\n3.6 Embedding Optimization\nEmbedding cost considerations\nCaching embeddings\nDeduplication\nWhen not to use embeddings\n4️⃣ Vector Databases',
        "page_number": 1,
        "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
    },
    {
        "content": "3.5 Chunking Strategies\nFixed-size chunking\nSentence-based chunking\nOverlapping chunks\nChunk size trade-offs\n3.6 Embedding Optimization\nEmbedding cost considerations\nCaching embeddings\nDeduplication\nWhen not to use embeddings\n4️⃣ Vector Databases\n4.1 Vector Database Basics\nDifference from SQL and NoSQL\nVector indexing\nApproximate Nearest Neighbor (ANN)\n4.2 Core Concepts\nVectors\nMetadata\nIndexes\nDistance metrics\nFiltering with similarity search\n4.3 Types of Vector Databases\nManaged (Cloud)\nPinecone\nWeaviate Cloud\nQdrant Cloud\nSelf-Hosted / Open Source\nFAISS\nChroma\nQdrant\nMilvus\nHybrid (Vector + SQL)\nPostgreSQL + pgvector\nElasticsearch (dense vectors)\n4.4 Vector Database Operations\nUpsert\nDelete\nQuery\nMetadata filtering\nNamespaces / collections\n4.5 Vector Database Selection Criteria\nDataset size\nLatency requirements\nCost considerations\nCloud vs self-hosted\nFiltering capabilities\n5️⃣ Hallucinations\n5.1 Hallucination Basics\nFactual hallucinations\nFabricated information\nFalse citations\nLogical inconsistencies\n5.2 Causes of Hallucinations\nKnowledge gaps\nAmbiguous prompts\nOver-generalization\nContext limitations\nTraining cutoff\n5.3 Types of Hallucinations\nFactual hallucination",
        "page_number": 1,
        "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
    },
    {
        "content": "Fabricated information\nFalse citations\nLogical inconsistencies\n5.2 Causes of Hallucinations\nKnowledge gaps\nAmbiguous prompts\nOver-generalization\nContext limitations\nTraining cutoff\n5.3 Types of Hallucinations\nFactual hallucination\nLogical hallucination\nSource hallucination\nInstruction hallucination\n5.4 Hallucination Mitigation\nPrompt-Level\nClear instructions\nExplicit uncertainty handling\nCitation requests\nStructured outputs\nData-Level\nRetrieval Augmented Generation\nHigh-quality context\nRelevant chunking\nModel-Level\nLower temperature\nAppropriate model selection\nSystem-Level\nOutput validation\nGuardrails\nPost-processing checks\n5.5 Evaluation & Testing\nGolden datasets\nPrompt regression testing\nManual evaluation\nHuman-in-the-loop review\n6️⃣ Types of GenAI APIs (for Integration)\nText / Chat APIs (ChatGPT, Gemini, Claude, Grok)\nEmbeddings APIs\nImage Generation APIs\nVision (Image Understanding) APIs\nAudio APIs (Speech-to-Text, Text-to-Speech)\nModeration / Safety APIs\nFine-Tuning APIs\nCloud-Hosted LLM APIs (Azure OpenAI, AWS Bedrock, Vertex AI)\nOpen-Source / Self-Hosted Model APIs",
        "page_number": 1,
        "document_id": "2efca688-634b-43da-bf7d-ab714d8adbf3",
    },
]
