"""added table

Revision ID: 37b2c78410c9
Revises: 873a7776aa14
Create Date: 2026-03-06 15:03:58.622150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b2c78410c9'
down_revision: Union[str, Sequence[str], None] = '873a7776aa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.create_foreign_key(None, 'documents', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    # ### end Alembic commands ###
