"""update models

Revision ID: 59b4a208876d
Revises: e03383a85a84
Create Date: 2026-03-05 12:51:23.348390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b4a208876d'
down_revision: Union[str, Sequence[str], None] = 'e03383a85a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('documents', 'session_id')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
